# Frontend Developer Role
name: "Frontend Developer"
description: "Web applications, UI/UX, and client-side development"
version: "2.0"
author: "Mac Setup Team"
last_updated: "2025-01-26"
minimum_macos: "13.0"
tags: ["frontend", "javascript", "typescript", "react", "vue", "css", "ui-ux"]
icon: "🎨"

brew_formulae:
  # Core Runtime
  - name: node
    description: "JavaScript runtime"
  
  # Package Managers
  - name: pnpm
    description: "Fast, efficient package manager"
    alternatives:
      - name: yarn
        description: "Alternative package manager"
  
  # Build Tools
  - name: watchman
    description: "File watching service"
  - name: mkcert
    description: "Local HTTPS certificates"
  
  # Image Optimization
  - name: imagemagick
    description: "Image manipulation"
  - name: jpegoptim
    description: "JPEG optimizer"
    optional: true
  - name: optipng
    description: "PNG optimizer"
    optional: true
  - name: svgo
    description: "SVG optimizer"
    optional: true
  
  # API Testing
  - name: httpie
    description: "User-friendly HTTP client"
  
  # Browser Testing
  - name: selenium-server
    description: "Browser automation"
    optional: true
  - name: chromedriver
    description: "Chrome automation"
    optional: true

brew_casks:
  # Code Editors
  - name: visual-studio-code
    description: "Primary code editor"
    alternatives:
      - name: cursor
        description: "AI-powered VS Code fork"
      - name: webstorm
        description: "JetBrains IDE for JavaScript"
        paid: true
  
  # Design Tools
  - name: figma
    description: "UI/UX design tool"
  - name: sketch
    description: "Mac design tool"
    optional: true
    paid: true
  
  # API Testing
  - name: postman
    description: "API testing platform"
    alternatives:
      - name: insomnia
        description: "Lightweight API client"
  
  # Browser DevTools
  - name: responsively
    description: "Test responsive designs"
    optional: true
  
  # Version Control
  - name: github
    description: "GitHub Desktop"
  - name: fork
    description: "Git GUI client"
    alternatives:
      - name: sourcetree
        description: "Free Git GUI"
  
  # Color Tools
  - name: colorsnapper
    description: "Color picker"
    optional: true
    paid: true

npm_packages:
  # Core Development
  - name: typescript
    description: "TypeScript compiler"
  - name: prettier
    description: "Code formatter"
  - name: eslint
    description: "JavaScript linter"
  - name: stylelint
    description: "CSS linter"
    optional: true
  
  # Dev Servers & Tools
  - name: vite
    description: "Next generation frontend tooling"
  - name: serve
    description: "Static file server"
  - name: http-server
    description: "Simple HTTP server"
  - name: browser-sync
    description: "Live-reload dev server"
    optional: true
  
  # Build Tools
  - name: webpack-cli
    description: "Module bundler CLI"
    optional: true
  - name: parcel
    description: "Zero-config build tool"
    optional: true
  
  # CSS Tools
  - name: sass
    description: "CSS preprocessor"
    optional: true
  - name: postcss-cli
    description: "CSS transformer"
    optional: true
  - name: tailwindcss
    description: "Utility-first CSS"
    optional: true
  
  # Testing Tools
  - name: jest
    description: "JavaScript testing"
    optional: true
  - name: cypress
    description: "E2E testing"
    optional: true
  - name: playwright
    description: "Cross-browser testing"
    optional: true
  
  # Framework CLIs (ask which ones)
  - name: create-react-app
    description: "React app generator"
    optional: true
  - name: "@angular/cli"
    description: "Angular CLI"
    optional: true
  - name: "@vue/cli"
    description: "Vue CLI"
    optional: true
  - name: create-next-app
    description: "Next.js generator"
    optional: true
  - name: "@sveltejs/kit"
    description: "SvelteKit CLI"
    optional: true

css_frameworks:
  # Ask preferences
  - tailwindcss
  - bootstrap
  - bulma
  - material-ui
  - ant-design

javascript_frameworks:
  # Ask preferences
  - react
  - vue
  - angular
  - svelte
  - solid
  - qwik

aliases:
  - "alias ns='npm start'"
  - "alias nr='npm run'"
  - "alias nb='npm run build'"
  - "alias nt='npm test'"
  - "alias ni='npm install'"
  - "alias dev='npm run dev'"

role_indicators:
  commands:
    - node
    - npm
    - pnpm
    - yarn
  files:
    - package.json
    - tsconfig.json
    - webpack.config.js
    - vite.config.js
    - .eslintrc.js
  directories:
    - node_modules
    - src
    - public
    - components
    - styles

dependencies:
  system:
    - xcode-select
    - git
  roles:
    - base-developer

post_install_notes: |
  Frontend Developer Setup Complete! 🎨
  
  Next steps:
  1. Choose your framework and create a project:
     - React: npx create-react-app my-app --template typescript
     - Vue: npm create vue@latest
     - Angular: ng new my-app
     - Svelte: npm create svelte@latest my-app
     - Next.js: npx create-next-app@latest
  
  2. Set up your design workflow:
     - Open Figma for UI design
     - Configure VS Code with extensions:
       • ESLint, Prettier, Tailwind CSS IntelliSense
       • Auto Rename Tag, Color Highlight
  
  3. Configure local HTTPS for development:
     - mkcert -install
     - mkcert localhost
  
  4. Set up CSS framework (if desired):
     - Tailwind: npm install -D tailwindcss
     - Bootstrap: npm install bootstrap
  
  5. Configure testing:
     - Jest: already installed globally
     - Cypress: npx cypress open
     - Playwright: npx playwright test

common_workflows:
  create_vite_project: |
    npm create vite@latest my-app
    cd my-app
    npm install
    npm run dev
  
  create_next_app: |
    npx create-next-app@latest my-app \
      --typescript \
      --tailwind \
      --app \
      --src-dir
    cd my-app
    npm run dev
  
  setup_tailwind: |
    npm install -D tailwindcss postcss autoprefixer
    npx tailwindcss init -p
    # Add to CSS: @tailwind base; @tailwind components; @tailwind utilities;
  
  component_library: |
    # React component with Storybook
    npx storybook@latest init
    npm run storybook
  
  performance_testing: |
    # Lighthouse CI
    npm install -g @lhci/cli
    lhci autorun
  
  responsive_testing: |
    # Using Responsively app
    open -a Responsively
    # Or browser-sync
    browser-sync start --server --files "*.html, css/*.css"

health_checks:
  commands:
    - node --version
    - npm --version
    - pnpm --version || echo "pnpm not installed"
  files:
    - ~/.npmrc
  dev_server:
    - "curl -f http://localhost:3000 || echo 'No dev server running'"
    - "curl -f http://localhost:5173 || echo 'No Vite server running'"
  browser_tools:
    - "which chromedriver || echo 'ChromeDriver not installed'"

estimated_install_time: "15-25 minutes"
disk_space_required: "5GB"
related_roles:
  - fullstack
  - mobile-developer
  - ui-ux-designer